// Cross-language parity: budgetForPurpose + isReasoningModel.
//
// Reads `test/parity/fixtures/budgets.json` (generated by Python via
// `scripts/build_parity_fixtures.py`) and asserts every case's TS output
// matches the Python-recorded expected output. If this drifts:
//   - The Python implementation changed → regenerate the fixture.
//   - The TS port diverged → fix TS to match.

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import {
  type BudgetCfg,
  budgetForPurpose,
} from "../../src/core/budgets.js";
import { isReasoningModel } from "../../src/core/provider-caps.js";

interface BudgetCase {
  label: string;
  purpose: string;
  provider: string | null;
  model: string | null;
  cfg: BudgetCfg;
  expected: {
    budget: number | null;
    /** Python may emit `None` when no model was supplied; we mirror as null. */
    reasoning: boolean | null;
  };
}

interface Fixture {
  module: string;
  case_count: number;
  cases: readonly BudgetCase[];
}

const FIXTURE_PATH = new URL("./fixtures/budgets.json", import.meta.url);
const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;

describe(`parity: budgets (${fixture.case_count} cases)`, () => {
  it("fixture file loaded", () => {
    expect(fixture.module).toBe("budgets");
    expect(fixture.cases.length).toBe(fixture.case_count);
    expect(fixture.cases.length).toBeGreaterThan(100);
  });

  it.each(fixture.cases.map((c) => [c.label, c] as const))(
    "%s",
    (_label, c) => {
      const budget = budgetForPurpose(
        c.purpose,
        c.provider ?? undefined,
        c.model ?? undefined,
        c.cfg,
      );
      expect(budget).toBe(c.expected.budget);

      // Reasoning-class detection: only check when both provider and model
      // were supplied (Python's _is_reasoning_model returns False for
      // missing model, but the fixture marks `reasoning: null` to flag
      // the no-provider rows).
      if (c.expected.reasoning !== null) {
        expect(isReasoningModel(c.provider ?? "", c.model ?? "")).toBe(
          c.expected.reasoning,
        );
      }
    },
  );
});
