// Cross-language parity: native tool_pick (Phase 5 part 3).
//
// Loads test/parity/fixtures/pick.json — generated by
// `scripts/build_parity_fixtures.py pick` — which records:
//   - args:     the input passed to tool_pick
//   - canned:   {provider_name: response_text} the LLM "returned"
//   - expected: Python's tool_pick output, sanitized
//
// The TS test wires `canned` into synthetic Providers whose .send()
// returns the matching text verbatim, then runs `runPick` and
// canonicalize-compares output (after the same sanitizer) to
// `expected`.
//
// Sanitizer strips the tail fields that depend on session/usage/timing
// /run_summary subsystems we haven't ported yet (budget, session,
// usage rollup, timing rollup, run_summary).

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { canonicalize } from "../../src/core/canonicalize.js";
import { runPick } from "../../src/tools/pick.js";
import { emptyUsage } from "../../src/core/usage.js";

import type { Provider, SendArgs, SendResult } from "../../src/providers/types.js";

interface PickCase {
  label:    string;
  args:     Record<string, unknown>;
  canned:   Record<string, string>;
  expected: Record<string, unknown>;
}
interface Fixture {
  module: string;
  case_count: number;
  cases: readonly PickCase[];
}

const HERE = path.dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(
  readFileSync(path.resolve(HERE, "fixtures", "pick.json"), "utf8"),
) as Fixture;

/** Build a synthetic Provider that returns the canned text verbatim.
 *  Usage shape mirrors what the Python fixture builder injects. */
function syntheticProvider(name: string, cannedText: string): Provider {
  return {
    name,
    model: `${name}-default`,
    send: async (args: SendArgs): Promise<SendResult> => ({
      text: cannedText,
      attempts: 1,
      usage: {
        ...emptyUsage(name, `${name}-default`, args.purpose ?? "worker"),
        prompt_tokens:     100,
        completion_tokens: 50,
        total_tokens:      150,
        estimated:         false,
      },
    }),
  };
}

/** Strip non-deterministic / not-yet-ported tail fields. */
function sanitize(out: Record<string, unknown>): Record<string, unknown> {
  const r = { ...out };
  for (const k of ["usage", "timing", "run_summary", "budget", "session",
                   "_suppress_run_summary"]) {
    delete r[k];
  }
  return r;
}

describe(`pick parity (${fixture.case_count} cases)`, () => {
  for (const c of fixture.cases) {
    it(c.label, async () => {
      const providers: Record<string, Provider> = {};
      for (const [name, text] of Object.entries(c.canned)) {
        providers[name] = syntheticProvider(name, text);
      }
      // Python's tool_pick uses the `model` field from the actual
      // provider object. The canned model in the fixture is
      // "{provider}-default" (matches what Python does when the
      // provider's default_model lookup falls through), so our
      // synthetic provider needs to emit the same name in usage.
      const actual = (await runPick(c.args, { providers })) as Record<string, unknown>;

      const exp = canonicalize(sanitize(c.expected));
      const act = canonicalize(sanitize(actual));
      expect(act).toBe(exp);
    });
  }
});
