// Cross-language parity: calculateCost.
//
// Reads `test/parity/fixtures/pricing.json` (generated by Python via
// `scripts/build_parity_fixtures.py`). The fixture embeds the pricing
// doc used to generate the goldens so the TS test doesn't depend on
// the repo-level config/pricing.json (which could drift independently).

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { calculateCost, type PricingDoc } from "../../src/core/pricing.js";

interface PricingCase {
  label: string;
  provider: string;
  model: string;
  prompt_tokens: number;
  completion_tokens: number;
  cached_tokens: number;
  expected: { cost_usd: number; estimated: boolean };
}

interface Fixture {
  module: string;
  case_count: number;
  pricing_doc: PricingDoc;
  cases: readonly PricingCase[];
}

const FIXTURE_PATH = new URL("./fixtures/pricing.json", import.meta.url);
const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;

describe(`parity: pricing (${fixture.case_count} cases)`, () => {
  it("fixture file loaded with embedded pricing doc", () => {
    expect(fixture.module).toBe("pricing");
    expect(fixture.pricing_doc).toBeTypeOf("object");
    expect(fixture.cases.length).toBe(fixture.case_count);
  });

  it.each(fixture.cases.map((c) => [c.label, c] as const))(
    "%s",
    (_label, c) => {
      const result = calculateCost(
        fixture.pricing_doc,
        c.provider,
        c.model,
        c.prompt_tokens,
        c.completion_tokens,
        c.cached_tokens,
      );
      // estimated must be a strict bool match.
      expect(result.estimated).toBe(c.expected.estimated);
      // cost_usd: byte-equal after Python's round(_, 8). Use toBe rather
      // than toBeCloseTo so we surface ANY drift, not just visible drift.
      expect(result.cost_usd).toBe(c.expected.cost_usd);
    },
  );
});
