// Cross-language parity: prompt adapters.
//
// Reads `test/parity/fixtures/prompts.json` (generated by Python via
// `scripts/build_parity_fixtures.py`).

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import {
  adaptMessages,
  anthropicXmlWrap,
  stripReasoningPreamble,
  type ChatMessage,
} from "../../src/core/prompts.js";

interface StripCase {
  label: string;
  messages: readonly ChatMessage[];
  expected: { messages: readonly ChatMessage[]; edits: number };
}
interface WrapCase extends StripCase {}
interface AdaptCase {
  label: string;
  provider: string;
  model: string;
  purpose: string;
  config?: { prompt_adapters?: { enabled?: boolean } };
  messages: readonly ChatMessage[];
  expected: { messages: readonly ChatMessage[]; applied: readonly string[] };
}

interface Fixture {
  module: string;
  case_count: number;
  strip_cases: readonly StripCase[];
  wrap_cases: readonly WrapCase[];
  adapt_cases: readonly AdaptCase[];
}

const fixture = JSON.parse(
  readFileSync(new URL("./fixtures/prompts.json", import.meta.url), "utf8"),
) as Fixture;

describe(`parity: prompts (${fixture.case_count} cases)`, () => {
  it("fixture loaded", () => {
    expect(fixture.module).toBe("prompts");
  });

  it.each(fixture.strip_cases.map((c) => [c.label, c] as const))(
    "%s",
    (_label, c) => {
      const r = stripReasoningPreamble(c.messages);
      expect(r.messages).toEqual(c.expected.messages);
      expect(r.edits).toBe(c.expected.edits);
    },
  );

  it.each(fixture.wrap_cases.map((c) => [c.label, c] as const))(
    "%s",
    (_label, c) => {
      const r = anthropicXmlWrap(c.messages);
      expect(r.messages).toEqual(c.expected.messages);
      expect(r.edits).toBe(c.expected.edits);
    },
  );

  it.each(fixture.adapt_cases.map((c) => [c.label, c] as const))(
    "%s",
    (_label, c) => {
      // The fixture's config field encodes whether adapters were enabled
      // when the golden was recorded. Default = enabled.
      const cfg = c.config?.prompt_adapters ?? { enabled: true };
      const r = adaptMessages(c.provider, c.model, c.purpose, c.messages, cfg);
      expect(r.messages).toEqual(c.expected.messages);
      expect(r.info.applied).toEqual(c.expected.applied);
    },
  );
});
