// Cross-language parity: native tool_verify (Phase 5 part 1).
//
// Reads `test/parity/fixtures/verify.json` (generated by Python via
// `scripts/build_parity_fixtures.py verify`) and asserts every case's
// TS output matches the Python-recorded expected output BYTE-EQUAL via
// canonicalize, after stripping non-deterministic fields:
//   - `timing.{wall_ms, cpu_ms}` — clock-dependent, omitted by sanitizer
//   - `run_summary`              — DB/session-dependent, omitted by sanitizer
//
// One additional language-divergence we normalize per-side:
//   - regex bad-pattern reasons embed Python's `re` error message in
//     Python, and JS's `SyntaxError` in TS. They will never match
//     byte-for-byte. We replace the inner message with `<msg>` on both
//     sides so the rest of the string (kind, label, structure) is
//     still proven equal.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { canonicalize } from "../../src/core/canonicalize.js";
import { runVerify } from "../../src/tools/verify.js";

interface VerifyCase {
  label:    string;
  args:     Record<string, unknown>;
  expected: Record<string, unknown>;
}

interface Fixture {
  module:      string;
  description: string;
  case_count:  number;
  cases:       readonly VerifyCase[];
}

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = path.resolve(HERE, "fixtures", "verify.json");
const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;

/** Strip non-deterministic fields. Applied to BOTH sides before compare. */
function sanitize(out: Record<string, unknown>): Record<string, unknown> {
  const r = { ...out };
  delete r["timing"];
  delete r["run_summary"];
  // Normalize regex bad-pattern reasons (Python's `re` error vs JS's
  // RegExp error will never match byte-for-byte). Replace the inner
  // message with a placeholder so the rest stays comparable.
  if (Array.isArray(r["results"])) {
    r["results"] = (r["results"] as unknown[]).map((row) => {
      if (typeof row !== "object" || row === null) return row;
      const o = { ...(row as Record<string, unknown>) };
      const reason = o["reason"];
      if (typeof reason === "string") {
        o["reason"] = reason.replace(
          /^failed: regex_match\[bad pattern: .*\]$/,
          "failed: regex_match[bad pattern: <msg>]",
        );
      }
      return o;
    });
  }
  return r;
}

describe(`verify parity (${fixture.case_count} cases)`, () => {
  for (const c of fixture.cases) {
    it(c.label, async () => {
      // No bridge in parity tests — pure native exercise. shell /
      // url_head fixtures use the no-bridge code paths which return
      // a clear error envelope; that matches Python's behavior for
      // shell-disabled (the only shell/url_head fixture).
      const actual = (await runVerify(c.args, undefined)) as Record<string, unknown>;
      const expectedCanon = canonicalize(sanitize(c.expected));
      const actualCanon   = canonicalize(sanitize(actual));
      expect(actualCanon).toBe(expectedCanon);
    });
  }
});
